// Renders every gallery screen for every profile and orientation into design/screens/, and
// bundles them with the tokens and icon paths into design/preview/data.js for the browser preview.
import { mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createKit, profileIds, tokens, screenBytes, type Screen } from "@quireos/ui";
import { SCREENS, SECTIONS, supports } from "../src/screens.js";

const here = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(here, "../../../../..");
const OUT = resolve(REPO, "design/screens");
rmSync(OUT, { recursive: true, force: true });

const all: Record<string, Record<string, Record<string, Screen>>> = {};
const report: string[] = [];
let count = 0, worst = { bytes: 0, widgets: 0, where: "" };
for (const profile of profileIds) {
  all[profile] = {};
  for (const orientation of ["portrait", "landscape"] as const) {
    all[profile]![orientation] = {};
    const dir = resolve(OUT, profile, orientation);
    mkdirSync(dir, { recursive: true });
    const deviceClass = tokens.profiles[profile].class;
    for (const [id, build] of Object.entries(SCREENS)) {
      if (!supports(id, deviceClass)) continue;
      // Page 1 tells us how many pages this screen takes on this panel; then we render the rest.
      let pages = 1;
      for (let p = 1; p <= pages && p <= 24; p++) {
        const ui = createKit({ profile, orientation });
        const screen = build(ui, p);
        if (p === 1) pages = Math.max(pages, ui.pageCount);
        const key = p > 1 ? `${id}?p=${p}` : id;
        const problems = ui.validate(screen);
        const bytes = screenBytes(screen);
        const widgets = JSON.stringify(screen).match(/"type":"/g)?.length ?? 0;
        if (bytes > worst.bytes) worst = { bytes, widgets, where: `${profile}/${orientation}/${key}` };
        if (problems.length) report.push(`${profile}/${orientation}/${key}: ${problems.map((x) => `${x.path} ${x.message}`).join("; ")}`);
        writeFileSync(resolve(dir, `${screen.id}.json`), JSON.stringify(screen, null, 1) + "\n");
        all[profile]![orientation]![key] = screen;
        count++;
      }
    }
  }
}
// A screen that links to a page nobody generated is a dead end on the device. Check every
// navigate target against what was written, for every profile and orientation.
for (const [profile, orientations] of Object.entries(all)) {
  for (const [orientation, screens] of Object.entries(orientations)) {
    for (const [key, screen] of Object.entries(screens)) {
      const targets: string[] = [];
      const walk = (w: unknown): void => {
        if (!w || typeof w !== "object") return;
        const o = w as Record<string, unknown>;
        for (const a of ["on_tap", "on_hold"]) {
          const act = o[a] as { type?: string; url?: string } | undefined;
          if (act?.type === "navigate" && typeof act.url === "string") targets.push(act.url);
        }
        for (const k of ["short", "double"]) {
          const act = (o.keys as Record<string, { type?: string; url?: string }> | undefined)?.[k];
          if (act?.type === "navigate" && typeof act.url === "string") targets.push(act.url);
        }
        for (const v of Object.values(o)) if (Array.isArray(v)) v.forEach(walk); else if (v && typeof v === "object") walk(v);
      };
      screen.widgets.forEach(walk);
      walk(screen);
      for (const url of targets) {
        const m = /^\/screens\/([a-z][a-z0-9-]*)\.json(?:\?p=(\d+))?$/.exec(url);
        if (!m) { report.push(`${profile}/${orientation}/${key}: unparseable link ${url}`); continue; }
        const want = m[2] && Number(m[2]) > 1 ? `${m[1]}?p=${m[2]}` : m[1]!;
        if (!(want in screens)) report.push(`${profile}/${orientation}/${key}: links to ${url}, which was never generated`);
      }
    }
  }
}

const paths = JSON.parse(readFileSync(resolve(REPO, "design/icons/paths.json"), "utf8"));
const fonts = JSON.parse(readFileSync(resolve(REPO, "spec/fonts.json"), "utf8"));
const data = { generated: new Date().toISOString().slice(0, 10), sections: SECTIONS, tokens, icons: paths, fonts, screens: all };
writeFileSync(resolve(REPO, "design/preview/data.js"), `// GENERATED by cloudflare/apps/gallery/scripts/build.ts. Do not edit.\nwindow.QUIRE_GALLERY = ${JSON.stringify(data)};\n`);
writeFileSync(resolve(OUT, "README.md"), `# Reference screens\n\nGENERATED by \`npm run build -w apps/gallery\` from [cloudflare/apps/gallery/src/screens.ts](../../cloudflare/apps/gallery/src/screens.ts): every gallery screen for every profile and orientation, as the spec JSON the device would receive. Open [../preview/index.html](../preview/index.html) to see them. ${count} screens; largest is ${worst.where} at ${worst.bytes} bytes.\n${report.length ? "\n## Validation problems\n\n" + report.map((r) => `- ${r}`).join("\n") + "\n" : "\nAll screens validate.\n"}`);
console.log(`gallery: ${count} screens -> design/screens, design/preview/data.js; largest ${worst.where} ${worst.bytes} B`);
if (report.length) {
  console.error(`\n${report.length} screen(s) did not validate:\n` + report.map((r) => `  ${r}`).join("\n"));
  process.exitCode = 1;
}
