// Bitmap font tables and a small anti-aliased blitter for the 4-bit logical framebuffer.
//
// The tables are generated by tools/gen_fonts.py from the Roboto TTFs and use the same packing as
// epdiy's fontconvert.py (4 bits per pixel, two pixels per byte, low nibble = left pixel, one row of
// ceil(width / 2) bytes per glyph line, 15 = fully inked), so the structs are layout-compatible with
// EpdFont. This blitter is our own MIT code; nothing here depends on epdiy.
#pragma once
#include <stddef.h>
#include <stdint.h>
#include "../hal/hal.h"

namespace quire {
namespace fontlib {

struct Glyph {
  uint16_t width, height, advance_x;
  int16_t left, top;
  uint32_t size;          // bytes of bitmap data (uncompressed)
  uint32_t data_offset;   // into Font::bitmap
};
struct Interval { uint32_t first, last, offset; };
struct Font {
  const uint8_t *bitmap;
  const Glyph *glyph;
  const Interval *intervals;
  uint32_t interval_count;
  bool compressed;        // always false for our tables
  uint16_t advance_y;     // line height
  int ascender;           // baseline offset from the top of a line box
  int descender;          // negative
};

enum class Size : uint8_t { XS = 0, SM, MD, LG, XL, XXL, XXXL, DIGITS, COUNT };
enum class Weight : uint8_t { REGULAR = 0, BOLD = 1 };

const char *size_name(Size s);
bool size_from_name(const char *name, Size &out);     // "xs".."3xl","digits"
bool weight_from_name(const char *name, Weight &out);

// The compiled-in font for a size/weight (digits ignores weight). Never null.
const Font *font(Size s, Weight w);
const Glyph *glyph(const Font *f, uint32_t code_point);   // null when missing
uint32_t fallback_code_point();                           // drawn for missing glyphs

// UTF-8 → code point; advances *s. Returns 0 at end of string.
uint32_t utf8_next(const char **s);

// Sum of glyph advances (no kerning). Missing glyphs count as the fallback glyph.
int text_width(const Font *f, const char *s, size_t len);
int text_width(const Font *f, const char *s);

// Draw one line of text with the baseline at (x, y). Colour 0..15; anti-aliased edges are blended
// against the framebuffer. Drawing is clipped to `clip`. Returns the x after the last glyph.
int draw_text(hal::Framebuffer &fb, const Font *f, const char *s, size_t len, int x, int y,
              uint8_t color, const hal::Rect &clip);

}  // namespace fontlib
}  // namespace quire
