// Generated by tools/gen_fonts.py from design/tokens/tokens.json for profile t5pro. Do not edit.
#pragma once
namespace quire { namespace profile {
static const char NAME[] = "t5pro";
static const int DPI = 235, GREYS = 16, UNIT = 4;
static const int MARGIN = 24, GUTTER = 16, INSET = 16, GAP = 8;
static const int STATUS = 44, NAV = 56, TOOLBAR = 56, RAIL = 80, CORNER = 48, TOAST = 56;
static const int ICON_SM = 32, ICON_MD = 48, ICON_LG = 96;
static const int TOUCH_MIN = 64, TOUCH_ROW = 56;
static const int RADIUS_SM = 4, RADIUS_MD = 8, RADIUS_LG = 16;
static const int STROKE_HAIRLINE = 1, STROKE_RULE = 1, STROKE_FRAME = 2;
// Tones (light): ink levels 0..15
static const int TONE_PAPER = 15, TONE_INK = 0, TONE_SECONDARY = 6, TONE_TERTIARY = 9, TONE_HAIRLINE = 10, TONE_FILL_SUBTLE = 13, TONE_FILL_DISABLED = 13;
}}
