#!/usr/bin/env node
// Builds the QuireOS icon library from vocab.json + @mdi/svg:
//   icons.json  the manifest apps and the kit read (names, roles, pairs, categories, sizes per profile)
//   paths.json  name -> SVG path data (24x24 viewBox) for the preview renderer and the contact sheet
//   names.txt   the plain list in the exact format firmware/tools/gen_icons.py keeps in ICONS
//   sheet.svg   a contact sheet for ICONS.md
// Fails if a vocabulary name does not exist in the pinned @mdi/svg version.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const vocab = JSON.parse(readFileSync(resolve(here, "vocab.json"), "utf8"));
const tokens = JSON.parse(readFileSync(resolve(here, "../tokens/tokens.json"), "utf8"));
const mdiDir = resolve(here, "node_modules/@mdi/svg");
if (!existsSync(mdiDir)) throw new Error("run `npm install` in design/icons first");
const mdiVersion = JSON.parse(readFileSync(resolve(mdiDir, "package.json"), "utf8")).version;

const seen = new Set();
const paths = {};
const missing = [];
for (const ic of vocab.icons) {
  if (seen.has(ic.name)) throw new Error(`duplicate icon ${ic.name}`);
  seen.add(ic.name);
  if (!vocab.categories[ic.category]) throw new Error(`${ic.name}: unknown category ${ic.category}`);
  const file = resolve(mdiDir, "svg", ic.name + ".svg");
  if (!existsSync(file)) { missing.push(ic.name); continue; }
  const svg = readFileSync(file, "utf8");
  const m = svg.match(/<path[^>]*\sd="([^"]+)"/);
  if (!m) throw new Error(`${ic.name}: no <path d> in svg`);
  paths[ic.name] = m[1];
}
if (missing.length) throw new Error(`not in @mdi/svg ${mdiVersion}: ${missing.join(", ")}`);
for (const ic of vocab.icons) if (ic.pair && !seen.has(ic.pair)) throw new Error(`${ic.name}: pair ${ic.pair} is not in the vocabulary`);
const roles = new Map();
for (const ic of vocab.icons) {
  if (roles.has(ic.role)) throw new Error(`role ${ic.role} used by ${roles.get(ic.role)} and ${ic.name}`);
  roles.set(ic.role, ic.name);
}

const sizes = Object.fromEntries(Object.entries(tokens.profiles).map(([id, p]) => [id, p.icon]));
// Flash budget. `core` icons are compiled into every firmware at sm and md; `extended` ones are
// compiled where flash allows (apps should fall back to a core icon or a PNG image elsewhere).
// Only `display` icons get the lg size, which costs four times a md bitmap.
const CORE = new Set(["navigation", "action", "selection", "status", "time", "weather", "home", "content"]);
// Roles the OS draws on its own screens (launcher, store, pairing, settings). They sit in
// categories that are otherwise extended, but a firmware that cannot draw its own Store tile is
// not a firmware, so they are core wherever they live.
const CORE_ROLES = new Set(["store", "store_filled", "paired", "account", "account_filled", "avatar", "sign_in", "sign_out", "github", "devices"]);
const DISPLAY_ROLES = new Set(["home", "apps", "search", "settings", "warning", "error", "info", "help", "success",
  "offline", "cloud_off", "update_available", "busy", "waiting", "sleep", "clock", "calendar", "clear_day",
  "clear_night", "partly_cloudy_day", "cloudy", "rain", "snow", "thunder", "light", "light_on", "lock",
  "unlock", "news", "read", "comments", "image", "email", "account", "store", "paired", "battery_low",
  "charging", "bookmark", "star", "favourite", "document", "wifi_off", "qr"]);
const icons = vocab.icons.map((ic) => ({
  name: ic.name, role: ic.role, category: ic.category,
  tier: CORE.has(ic.category) || CORE_ROLES.has(ic.role) ? "core" : "extended",
  style: ic.name.endsWith("-outline") || ic.name.includes("-outline-") ? "outline" : ic.pair ? "outline" : "solid",
  ...(DISPLAY_ROLES.has(ic.role) ? { display: true } : {}),
  ...(ic.pair ? { pair: ic.pair } : {}),
}));
const budget = { core: icons.filter((i) => i.tier === "core").length, extended: icons.filter((i) => i.tier === "extended").length, display: icons.filter((i) => i.display).length };
writeFileSync(resolve(here, "icons.json"), JSON.stringify({
  $comment: "GENERATED by design/icons/build.mjs from vocab.json. Do not edit.",
  spec_version: 1,
  source: { package: "@mdi/svg", version: mdiVersion, license: "Apache-2.0", author: "Pictogrammers" },
  count: icons.length,
  tiers: { core: "compiled into every firmware at sm and md", extended: "compiled where flash allows", display: "also compiled at lg" },
  budget,
  categories: vocab.categories,
  sizes,
  icons,
}, null, 2) + "\n");
writeFileSync(resolve(here, "paths.json"), JSON.stringify({ $comment: "GENERATED: MDI 24x24 path data per icon name.", viewBox: "0 0 24 24", paths }, null, 0) + "\n");

// names.txt in gen_icons.py's ICONS layout: space separated, wrapped at ~100 columns, sorted.
const names = [...seen].sort();
const lines = [];
let line = "";
for (const n of names) {
  if ((line + " " + n).length > 100) { lines.push(line.trim()); line = ""; }
  line += " " + n;
}
if (line.trim()) lines.push(line.trim());
writeFileSync(resolve(here, "names.txt"), lines.join("\n") + "\n");

// Contact sheet: grouped by category, 48 px cells, label under each.
const byCat = {};
for (const ic of vocab.icons) (byCat[ic.category] ||= []).push(ic);
const cell = 92, cellH = 76, cols = 8, pad = 16;
let y = pad, parts = [];
for (const [cat, list] of Object.entries(byCat)) {
  parts.push(`<text x="${pad}" y="${y + 18}" font-family="Roboto, Helvetica, Arial, sans-serif" font-size="16" font-weight="bold" fill="#000">${cat}</text>`);
  y += 30;
  list.forEach((ic, i) => {
    const cx = pad + (i % cols) * cell, cy = y + Math.floor(i / cols) * cellH;
    parts.push(`<g transform="translate(${cx},${cy})"><g transform="scale(2)"><path d="${paths[ic.name]}" fill="#000"/></g>` +
      `<text x="0" y="62" font-family="Roboto, Helvetica, Arial, sans-serif" font-size="9" fill="#444">${ic.name}</text></g>`);
  });
  y += Math.ceil(list.length / cols) * cellH + 12;
}
const sheet = `<svg xmlns="http://www.w3.org/2000/svg" width="${pad * 2 + cols * cell}" height="${y}" viewBox="0 0 ${pad * 2 + cols * cell} ${y}">` +
  `<rect width="100%" height="100%" fill="#fff"/>${parts.join("")}</svg>`;
writeFileSync(resolve(here, "sheet.svg"), sheet + "\n");
console.log(`icons: core ${budget.core}, extended ${budget.extended}, display(lg) ${budget.display}`);
console.log(`icons: ${icons.length} icons in ${Object.keys(byCat).length} categories from @mdi/svg ${mdiVersion} -> icons.json, paths.json, names.txt, sheet.svg`);
