// Regenerates src/generated/{tokens,icons,fonts}.ts from the design system's JSON so the kit has
// no runtime file access (it runs on Cloudflare Workers). Run via `npm run sync-design`, and as
// part of build, test and typecheck.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(here, "../../..");
const out = resolve(here, "../src/generated");
mkdirSync(out, { recursive: true });

function emit(name, source, exportName) {
  const json = JSON.parse(readFileSync(source, "utf8"));
  const body = `// GENERATED by scripts/sync-design.mjs from ${source.replace(REPO + "/", "")}. Do not edit.\n` +
    `const ${exportName} = ${JSON.stringify(json)} as const;\nexport default ${exportName};\n`;
  const file = resolve(out, name + ".ts");
  let existing = null;
  try { existing = readFileSync(file, "utf8"); } catch {}
  if (existing !== body) { writeFileSync(file, body); console.log(`sync-design: wrote ${name}.ts`); }
}
emit("tokens", resolve(REPO, "design/tokens/tokens.json"), "tokens");
emit("icons", resolve(REPO, "design/icons/icons.json"), "icons");
// What the firmware compiles, which is a subset of the library: an extended-tier name is a real
// icon but draws nothing on a board that did not compile it.
const specIcons = resolve(REPO, "spec/icons.json");
if (existsSync(specIcons)) emit("spec_icons", specIcons, "specIcons");
const fonts = resolve(REPO, "spec/fonts.json");
const sample = resolve(REPO, "cloudflare/sdk/test/fixtures/profile.sample.json");
emit("fonts", existsSync(fonts) ? fonts : sample, "fonts");
