#!/usr/bin/env python3
"""Gzip firmware/src/os/www/settings.html into settings_html_gz.h (served at GET /os)."""
import gzip
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "os", "www", "settings.html")
OUT = os.path.join(ROOT, "src", "os", "www", "settings_html_gz.h")

with open(SRC, "rb") as f:
    raw = f.read()
gz = gzip.compress(raw, compresslevel=9, mtime=0)
with open(OUT, "w") as o:
    o.write("// Generated by tools/gen_www.py from settings.html (%d bytes -> %d gzipped). Do not edit.\n" % (len(raw), len(gz)))
    o.write("#pragma once\n#include <stddef.h>\n#include <stdint.h>\n")
    o.write("static const uint8_t WWW_SETTINGS_GZ[%d] = {\n" % len(gz))
    for i in range(0, len(gz), 32):
        o.write(",".join(str(b) for b in gz[i:i + 32]) + ",\n")
    o.write("};\nstatic const size_t WWW_SETTINGS_GZ_LEN = %d;\n" % len(gz))
print("settings.html: %d bytes -> %d gzipped" % (len(raw), len(gz)))
