#!/usr/bin/env python3
"""Rasterise the design library's icon set (Material Design Icons, Apache-2.0, Pictogrammers) into
firmware/src/runtime/icons_gen.h and write spec/icons.json.

Reads design/icons/icons.json: the `core` tier is compiled at `sm` and `md`, icons flagged
`display` also at `lg`, and the `extended` tier only with --extended. Pixel sizes per profile come
from design/tokens/tokens.json (`profiles.<name>.icon`); the C tables are built for one board
profile (--profile, default t5pro), spec/icons.json lists the sizes of every profile.

Each bitmap is 4 bits per pixel of INK COVERAGE (15 = fully inked), two pixels per byte, low
nibble = left pixel, ceil(size/2) bytes per row: the same packing as the font glyphs.

Run:  uv pip install --python firmware/.venv/bin/python resvg-py pillow
      firmware/.venv/bin/python firmware/tools/gen_icons.py [--profile t5pro] [--extended]
"""
import argparse
import io
import json
import os
import sys
import tempfile
import urllib.request

try:
    import resvg_py
    from PIL import Image
except ImportError:
    sys.exit("pip install resvg-py pillow (see docstring)")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(ROOT)
OUT_H = os.path.join(ROOT, "src", "runtime", "icons_gen.h")
SPEC_JSON = os.path.join(REPO, "spec", "icons.json")
DESIGN_ICONS = os.path.join(REPO, "design", "icons", "icons.json")
DESIGN_PATHS = os.path.join(REPO, "design", "icons", "paths.json")
TOKENS = os.path.join(REPO, "design", "tokens", "tokens.json")
CACHE = os.path.join(tempfile.gettempdir(), "quireos-mdi")
BASE = "https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/%s.svg"
SIZE_KEYS = ["sm", "md", "lg"]


def load_svg(name, paths):
    """Prefer the path data pinned in design/icons/paths.json; fall back to fetching the SVG."""
    d = paths.get(name)
    if isinstance(d, dict):
        d = d.get("d") or d.get("path")
    if isinstance(d, str) and d:
        return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="%s"/></svg>' % d
    os.makedirs(CACHE, exist_ok=True)
    p = os.path.join(CACHE, name + ".svg")
    if not os.path.exists(p):
        with urllib.request.urlopen(BASE % name, timeout=30) as r:
            data = r.read()
        with open(p, "wb") as f:
            f.write(data)
    return open(p, encoding="utf-8").read()


def raster(svg, px):
    png = resvg_py.svg_to_bytes(svg_string=svg, width=px, height=px)
    im = Image.open(io.BytesIO(bytes(png))).convert("RGBA")
    assert im.size == (px, px), im.size
    a = im.getchannel("A").tobytes()
    rowbytes = (px + 1) // 2
    out = bytearray(rowbytes * px)
    for y in range(px):
        for x in range(px):
            v = (a[y * px + x] * 15 + 127) // 255
            i = y * rowbytes + x // 2
            out[i] |= (v << 4) if (x & 1) else v
    return bytes(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", default="t5pro", help="board profile whose pixel sizes go into the C tables")
    ap.add_argument("--extended", action="store_true", help="also compile the extended tier (sm, md)")
    args = ap.parse_args()

    icons = json.load(open(DESIGN_ICONS))
    tokens = json.load(open(TOKENS))
    paths = {}
    if os.path.exists(DESIGN_PATHS):
        try:
            paths = json.load(open(DESIGN_PATHS))
        except Exception:
            paths = {}
    sizes_by_profile = {name: dict(p["icon"]) for name, p in tokens["profiles"].items()}
    if args.profile not in sizes_by_profile:
        sys.exit("unknown profile %s (tokens.json has %s)" % (args.profile, list(sizes_by_profile)))
    px = sizes_by_profile[args.profile]

    selected = []   # (name, has_lg)
    for ic in icons["icons"]:
        tier = ic.get("tier", "core")
        if tier == "core" or (tier == "extended" and args.extended):
            selected.append((ic["name"], bool(ic.get("display"))))
    selected.sort()
    names = [n for n, _ in selected]
    lg_names = [n for n, lg in selected if lg]

    total = 0
    with open(OUT_H, "w") as o:
        o.write("// Generated by tools/gen_icons.py from design/icons/icons.json (Material Design Icons,\n")
        o.write("// Apache-2.0, Pictogrammers) for profile %s. 4 bpp ink coverage, two pixels per byte,\n" % args.profile)
        o.write("// low nibble = left pixel. lg bitmaps exist only for the `display` subset. Do not edit.\n")
        o.write("#pragma once\n#include <stdint.h>\nnamespace quire { namespace icons {\n")
        o.write("static const char PROFILE[] = \"%s\";\n" % args.profile)
        o.write("static const uint16_t SIZES[3] = {%d, %d, %d};\n" % (px["sm"], px["md"], px["lg"]))
        for name, has_lg in selected:
            svg = load_svg(name, paths)
            cname = name.replace("-", "_")
            for key in SIZE_KEYS:
                if key == "lg" and not has_lg:
                    continue
                bm = raster(svg, px[key])
                total += len(bm)
                o.write("static const uint8_t i_%s_%s[%d] = {\n" % (cname, key, len(bm)))
                for i in range(0, len(bm), 40):
                    o.write(",".join(str(b) for b in bm[i:i + 40]) + ",\n")
                o.write("};\n")
            print("  %-36s %s" % (name, "sm md lg" if has_lg else "sm md"), file=sys.stderr)
        o.write("struct Icon { const char *name; const uint8_t *bitmap[3]; };\n")
        o.write("static const Icon ICONS[] = {\n")
        for name, has_lg in selected:
            cname = name.replace("-", "_")
            refs = ["i_%s_sm" % cname, "i_%s_md" % cname, ("i_%s_lg" % cname) if has_lg else "nullptr"]
            o.write('  { "%s", { %s } },\n' % (name, ", ".join(refs)))
        o.write("};\nstatic const int COUNT = %d;\n}}  // namespace quire::icons\n" % len(selected))
    with open(SPEC_JSON, "w") as o:
        json.dump({"spec_version": 1, "source": icons.get("source"), "profile": args.profile,
                   "icons": names, "lg": lg_names, "sizes": sizes_by_profile}, o, indent=2)
        o.write("\n")
    print("%d icons (%d with lg), %.1f kB of bitmaps -> %s, %s" % (len(names), len(lg_names), total / 1024, OUT_H, SPEC_JSON), file=sys.stderr)


if __name__ == "__main__":
    main()
