// Generated by tools/gen_fonts.py for profile t5pro. Included from fontlib.cpp only.
#pragma once
#include "font_xs_regular.h"
#include "font_xs_bold.h"
#include "font_sm_regular.h"
#include "font_sm_bold.h"
#include "font_md_regular.h"
#include "font_md_bold.h"
#include "font_lg_regular.h"
#include "font_lg_bold.h"
#include "font_xl_regular.h"
#include "font_xl_bold.h"
#include "font_xxl_regular.h"
#include "font_xxl_bold.h"
#include "font_xxxl_regular.h"
#include "font_xxxl_bold.h"
#include "font_digits_bold.h"
namespace quire { namespace fonts {
// [size][weight]; digits uses the bold face for both weights.
static const fontlib::Font *const TABLE[8][2] = {
  { &font_xs_regular, &font_xs_bold },
  { &font_sm_regular, &font_sm_bold },
  { &font_md_regular, &font_md_bold },
  { &font_lg_regular, &font_lg_bold },
  { &font_xl_regular, &font_xl_bold },
  { &font_xxl_regular, &font_xxl_bold },
  { &font_xxxl_regular, &font_xxxl_bold },
  { &font_digits_bold, &font_digits_bold },
};
}}
